In [3]:
import numpy as np
# 1D array
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
#multi dimensional array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
# 'ndim' returns dimensions of array
print(arr.ndim)

2


In [6]:
# accessing array using index
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1[2])     # returns element with index 2
print(arr2[1,1])   # returns element with index arr[1][1]

3
5


In [9]:
# array slicing
print(arr1[1:-1])   # returns array from index 1 to last index with increment as 1
print(arr2[0,::2])  # returns array from index arr[0] 0 to last index with increment as 2
print(arr2[:2,1:])  # returns 2D array from both elements from index 1 to last index

[2 3]
[1 3]
[[2 3]
 [5 6]]


In [12]:
# array datatype

# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

print(arr1.dtype)                                             # returns datatype of elements of the array
print(np.array(["apple","banana","cherry"],dtype='S').dtype)  # returns datatype of elements of the array
arr3=arr1.astype("f")                                         # we can change datatype of elements using 'astype'
print(arr3)
print(arr3.dtype)

int32
|S6
[1. 2. 3. 4.]
float32


In [ ]:
# array copy vs view 

In [14]:
#copy creates a copy of array and returns it to new variable
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = -1
print(arr)     # changes made in original won't affect copied array
print(x)       # no Change

[-1  2  3  4  5]
[1 2 3 4 5]


In [15]:
#view refers to the same array and assigns it to new variable
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0] = 10  # changes made in arr will affect new variable
print("arr=",arr)
print("x=",x)
x[0] = 20    # changes made in x will affect arr
print("arr=",arr) 
print("x=",x)

arr= [10  2  3  4  5]
x= [10  2  3  4  5]
arr= [20  2  3  4  5]
x= [20  2  3  4  5]


In [20]:
# array shape
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3],[4,5,6]])
# shape returns number of dimension and number of elements in each dimension
print(arr1.shape)
print(arr2.shape)

(4,)
(2, 3)


In [26]:
# array reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr1 = arr.reshape(3,4) # this will create a 2D array with 3 rows and 4 columns
print(newarr1)
newarr2 = arr.reshape(3,1,4) # this will create a 3D array
print(newarr2)
# NOTE:- reshaping requires exact number of elements. More or less elements in new array will result in ERROR

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


In [28]:
# iterating arrays
arr=np.array([[1,2,3],[4,5,6]])
# iterating over 'n' dimensions array will require 'n' nested loops
# using 'nditer' we can iterate using one loop only
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [35]:
# concatenate arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.concatenate((arr1,arr2))
print(arr3)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
# using axis property we can concate multi dimension 
arr4=np.concatenate((arr1, arr2), axis=1)
print(arr4)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [36]:
# search in array
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)
x = np.where(arr%2 == 0)
print(x)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)


In [37]:
# sort array
arr=np.array([7,2,6,0,4])
print(np.sort(arr))

[0 2 4 6 7]


In [38]:
# add in array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.add(arr1,arr2))

[5 7 9]
